module.exports = {
  TOGGLEHEADER: 'TOGGLEHEADER',

  MESSAGES_RECEIVED: 'MESSAGES_RECEIVED',
  MESSAGE_TOGGLEALTERNATIVE: 'MESSAGE_TOGGLEALTERNATIVE',
  MESSAGE_DELETE: 'MESSAGE_DELETE',
  MESSAGE_EDIT: 'MESSAGE_EDIT',
  MESSAGE_UPDATE: 'MESSAGE_UPDATE',
  MESSAGE_ALERTDELETETOGGLE : 'MESSAGE_ALERTDELETETOGGLE',
  MESSAGE_DELETERESULTRECEIVED : 'MESSAGE_DELETERESULTRECEIVED',
  MESSAGE_CREATE: 'MESSAGE_CREATE',
  MESSAGE_CREATERESULTRECEIVED: 'MESSAGE_CREATERESULTRECEIVED',

  CONV_CREATE: 'CONV_CREATE',
  CONV_UPDATE: 'CONV_UPDATE',
  CONV_EDIT: 'CONV_EDIT',
  CONV_DELETE: 'CONV_DELETE',
  CONV_RECEIVED: 'CONV_RECEIVED',
  CONV_CLICKED: 'CONV_CLICKED',
  CONV_PLUS_HOVER: 'CONV_PLUS_HOVER',

  ALERT_MSGDELETE : 'ALERT_MSGDELETE',
  ALERT_CONFIRMMSGDELETE: 'ALERT_CONFIRMMSGDELETE'
}
