module.exports = {
  TOGGLEHEADER: 'TOGGLEHEADER',

  MESSAGES_RECEIVED: 'MESSAGES_RECEIVED',
   
  Q_CREATE: 'Q_CREATE',

  R_CREATE: 'R_CREATE',

  CONV_CREATE: 'CONV_CREATE',
  CONV_UPDATE: 'CONV_UPDATE',
  CONV_EDIT: 'CONV_EDIT',
  CONV_DELETE: 'CONV_DELETE',
  CONV_RECEIVED: 'CONV_RECEIVED',
  CONV_CLICKED: 'CONV_CLICKED'
}
